# Generated by Django 2.0.6 on 2018-07-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kik_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
