# Generated by Django 2.0.6 on 2018-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kik_profile', '0002_delete_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('post', models.CharField(max_length=500)),
                ('career_date', models.DateField(verbose_name='Career_Date')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
