# Generated by Django 2.0.7 on 2018-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kik_profile', '0003_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('career_date', models.DateField(verbose_name='Career_Date')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
