# Generated by Django 2.2.1 on 2019-05-27 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kik_profile', '0004_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='career_date',
        ),
        migrations.AddField(
            model_name='award',
            name='award_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Award_Date'),
            preserve_default=False,
        ),
    ]
